services:
   postgres:
     image: postgres:16
     restart: unless-stopped
     environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
     ports:
       - "5432:5432"
     volumes:
       - ./models/schema.sql:/docker-entrypoint-initdb.d/create_tables.sql